#!/bin/bash
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Alabama data/AL
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Arizona data/AZ
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Arkansas data/AR
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_California data/CA
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Colorado data/CO
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Connecticut data/CT
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Delaware data/DE
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Florida data/FL
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Georgia data/GA
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Hawaii data/HI
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Idaho data/ID
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Illinois data/IL
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Indiana data/IN
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Iowa data/IA
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Kansas data/KS
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Kentucky data/KY
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Louisiana data/LA
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Maine data/ME
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Maryland data/MD
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Massachusetts data/MA
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Michigan data/MI
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Minnesota data/MN
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Mississippi data/MS
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Missouri data/MO
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Montana data/MT
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Nebraska data/NE
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Nevada data/NV
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_New_Hampshire data/NH
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_New_Jersey data/NJ
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_New_Mexico data/NM
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_New_York data/NY
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_North_Carolina data/NC
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_North_Dakota data/ND
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Ohio data/OH
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Oklahoma data/OK
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Oregon data/OR
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Pennsylvania data/PA
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Rhode_Island data/RI
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_South_Carolina data/SC
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_South_Dakota data/SD
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Tennessee data/TN
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Texas data/TX
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Utah data/UT
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Vermont data/VT
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Virginia data/VA
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Washington data/WA
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_West_Virginia data/WV
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Wisconsin data/WI
node senator_scraper.js http://en.wikipedia.org/wiki/List_of_United_States_Senators_from_Wyoming data/WY
